
import React, { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Check, FileDown, Mail, Loader2, Database, AlertTriangle } from 'lucide-react';
import { GlassContainer } from '@/components/ui/glass-effects';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { toast } from '@/hooks/use-toast';
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { supabase } from '@/integrations/supabase/client';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ShipmentSuccessViewProps {
  onCreateAnother: () => void;
  shipmentData?: {
    id?: string;
    reference?: string;
    origin?: string;
    destination?: string;
    weight?: number;
    volume?: number;
    category?: string;
  };
}

const ShipmentSuccessView: React.FC<ShipmentSuccessViewProps> = ({ 
  onCreateAnother,
  shipmentData = {}
}) => {
  const [isEmailDialogOpen, setIsEmailDialogOpen] = useState(false);
  const [recipientEmail, setRecipientEmail] = useState('');
  const [isSendingEmail, setIsSendingEmail] = useState(false);
  const [emailResponse, setEmailResponse] = useState<any>(null);

  const generatePDF = () => {
    const doc = new jsPDF();
    
    doc.setFontSize(18);
    doc.text('Shipment Details', 105, 15, { align: 'center' });
    
    const reference = shipmentData.reference || shipmentData.id || 'New Shipment';
    doc.text(`Reference: ${reference}`, 105, 25, { align: 'center' });
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 105, 30, { align: 'center' });
    
    // Shipment details
    const yPosition = 40;
    doc.setFontSize(12);
    doc.text('Shipment Information', 14, yPosition);
    
    autoTable(doc, {
      startY: yPosition + 5,
      head: [['Field', 'Value']],
      body: [
        ['Reference', reference],
        ['Origin', shipmentData.origin || 'N/A'],
        ['Destination', shipmentData.destination || 'N/A'],
        ['Weight (kg)', shipmentData.weight?.toString() || 'N/A'],
        ['Volume (cbm)', shipmentData.volume?.toString() || 'N/A'],
        ['Category', shipmentData.category || 'N/A']
      ],
      theme: 'grid'
    });
    
    // Footer
    doc.setFontSize(10);
    doc.text('Generated by DeepCAL Operations Center', 105, (doc as any).lastAutoTable.finalY + 20, { align: 'center' });
    
    return doc;
  };

  const handleDownloadPDF = () => {
    const doc = generatePDF();
    const reference = shipmentData.reference || shipmentData.id || 'shipment';
    doc.save(`${reference}.pdf`);
    
    toast({
      title: "PDF Downloaded",
      description: "The shipment details have been downloaded as a PDF document."
    });
  };

  const handleOpenEmailDialog = () => {
    setIsEmailDialogOpen(true);
    setEmailResponse(null);
  };

  const handleSendEmail = async () => {
    // Email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(recipientEmail)) {
      toast({
        title: "Invalid Email",
        description: "Please enter a valid email address",
        variant: "destructive"
      });
      return;
    }
    
    setIsSendingEmail(true);
    
    try {
      const doc = generatePDF();
      const pdfBase64 = doc.output('datauristring').split(',')[1];
      const reference = shipmentData.reference || shipmentData.id || 'New Shipment';
      
      const { data, error } = await supabase.functions.invoke('send-rfq-email', {
        body: {
          recipientEmail,
          pdfBase64,
          rfqReference: reference,
          subject: `Shipment Details: ${reference}`,
          testMode: false
        }
      });
      
      if (error) {
        throw new Error(error.message || 'Failed to send email');
      }
      
      setEmailResponse(data);
      
      toast({
        title: "Email Sent",
        description: `The shipment details have been sent to ${recipientEmail}`
      });
    } catch (error) {
      console.error('Error sending email:', error);
      
      setEmailResponse({
        success: false,
        error: error instanceof Error ? error.message : "Failed to send the email. Please try again later."
      });
      
      toast({
        title: "Error",
        description: "Failed to send the email. Please try again later.",
        variant: "destructive"
      });
    } finally {
      setIsSendingEmail(false);
    }
  };

  const shipmentRef = shipmentData.reference || shipmentData.id || 'New Shipment';

  return (
    <>
      <GlassContainer className="max-w-4xl mx-auto p-8 mt-8">
        <div className="text-center">
          <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-green-100 dark:bg-green-900/30">
            <Check className="h-8 w-8 text-green-600 dark:text-green-400" />
          </div>
          <h3 className="mt-4 text-xl font-medium text-[#00FFD1]">Shipment Successfully Created</h3>
          <p className="mt-2 text-sm text-muted-foreground">
            Your new shipment has been registered in the system and saved to the database.
            You can track its progress in the Map view.
          </p>
          <div className="mt-3 flex justify-center">
            <div className="bg-blue-500/10 text-blue-400 rounded-full px-4 py-1 text-sm flex items-center">
              <Database className="h-3.5 w-3.5 mr-1.5" />
              Synced with database
            </div>
          </div>
          <div className="mt-6 flex flex-wrap justify-center gap-4">
            <Button 
              variant="outline" 
              className="border-[#00FFD1]/30 text-[#00FFD1] hover:bg-[#00FFD1]/10"
              onClick={handleDownloadPDF}
            >
              <FileDown className="mr-2 h-4 w-4" />
              Download Shipment Details
            </Button>
            <Button 
              variant="outline" 
              className="border-[#00FFD1]/30 text-[#00FFD1] hover:bg-[#00FFD1]/10"
              onClick={handleOpenEmailDialog}
            >
              <Mail className="mr-2 h-4 w-4" />
              Email Shipment Details
            </Button>
            <Button 
              variant="outline" 
              className="border-[#00FFD1]/30 text-[#00FFD1] hover:bg-[#00FFD1]/10"
              onClick={onCreateAnother}
            >
              Create Another Shipment
            </Button>
          </div>
        </div>
      </GlassContainer>

      {/* Email Dialog */}
      <Dialog open={isEmailDialogOpen} onOpenChange={setIsEmailDialogOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Send Shipment Details as PDF</DialogTitle>
          </DialogHeader>
          <div className="py-4">
            <Label htmlFor="email" className="mb-2 block">Recipient Email</Label>
            <Input
              id="email"
              type="email"
              placeholder="recipient@example.com"
              value={recipientEmail}
              onChange={(e) => setRecipientEmail(e.target.value)}
            />
            <p className="text-xs text-muted-foreground mt-2">
              Note: Make sure to check your spam folder if you don't see the email.
            </p>
          </div>
          
          {emailResponse && (
            <Alert variant={emailResponse.success ? "default" : "destructive"} className="my-2">
              <AlertTitle className="flex items-center">
                {emailResponse.success 
                  ? <><Check className="h-4 w-4 mr-2" /> Email Status</> 
                  : <><AlertTriangle className="h-4 w-4 mr-2" /> Email Error</>}
              </AlertTitle>
              <AlertDescription>
                {emailResponse.success 
                  ? emailResponse.message || "Email sent successfully" 
                  : emailResponse.error || "Failed to send email"}
              </AlertDescription>
            </Alert>
          )}
          
          <DialogFooter>
            <Button 
              variant="secondary" 
              onClick={() => setIsEmailDialogOpen(false)}
              disabled={isSendingEmail}
            >
              Close
            </Button>
            <Button 
              onClick={handleSendEmail}
              disabled={!recipientEmail || isSendingEmail}
            >
              {isSendingEmail ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Sending...
                </>
              ) : (
                "Send Email"
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
};

export default ShipmentSuccessView;
